import { type NextPage } from "next";
import Head from "next/head";
import { Layout } from "@/shared";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <Layout title="Home">
      <Head>
        <title>Expense Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Home page
      <Link href="chats">Chats page</Link>
      <Link href="movies">Movies page</Link>
    </Layout>
  );
};

export default Home;
